plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.78' apply false
}

group = 'lol.hisoka'
version = '0.1.0'

subprojects {
    apply plugin: 'java'

    group = rootProject.group
    version = rootProject.version

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
